### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Foso** [SteamDeckHomebrew/decky-playground#3]
Please add a license file to this project

**Comment by TrainDoctor** [comment]
~~Original author @JohnnyCrazy has been contacted and he or I will apply a license asap. Since he's the original author it's only fair that he chooses the license. I will add one regardless if need be at such time it's necessary.~~
Looks to be that the license according to the configuration files is GPL 2, I've added this license for now and will close the issue only when Johnny has weighed in.

**Comment by JohnnyCrazy** [comment]
I would've chosen MIT, will update it tomorrow
